config/routes.rb
Hulkort::Application.routes.draw do
  root to: 'pages#index'

  resources :users, only: [:edit, :update, :show]

  namespace :api do
    resources :commits, only: [:create]
    resources :repositories, only: [:create]
  end

  get 'graphs/:shortcode', to: 'graphs#show', as: :graph

  # Define the 'as:' option different from the named route that clearance provides
  # to prevent a naming conflict
  delete '/sign_out', to: 'sessions#destroy', as: :signout
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  belongs_to :user
  belongs_to :repository
  scope :limit_time_to, lambda { |timestamp| where('created_at >= ?', timestamp) }

  def self.daily_commits(number = 30)
    commits_by_date = Commit.where('created_at >= ?', number.days.ago).group_by { |commit| commit.created_at.strftime('%Y%m%d') }

    result = number.times.map do |day|
      date = day.days.ago.strftime('%Y%m%d')
      count = commits_by_date[date].present? ? commits_by_date[date].count : 0

      { "date" => date, "count" => count }
    end
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :user
  has_many :commits
  before_validation :generate_shortcode, :on => :create

  validates :name, :presence => true
  validates :shortcode, :presence => true, :uniqueness => true
  validates :name, :uniqueness => { :scope => :user_id }

  def generate_shortcode
    begin
      code = ([
        ("a".."z").to_a,
        ("A".."Z").to_a,
        ("0".."9").to_a].flatten
      ).sort_by{rand}[0,6].join
    end until code.to_i.zero? && code != '0' * 6 && Repository.find_by_shortcode(code).nil?

    self.shortcode = code
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  # use before_validation because before_create somehow breaks uniqueness in test env
  before_validation :generate_api_key, :on => :create

  validates :api_key, :uniqueness => true

  has_many :commits
  has_many :repositories

  private

  def generate_api_key
    begin
      key = Digest::SHA1.hexdigest(Time.now.to_s + rand(12341234).to_s)[1..24]
    end until User.find_by_api_key(key).nil?

    self.api_key = key
  end

end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  before_filter :authorize
  skip_before_filter :ensure_domain

  private
  def authorize
    if params[:api_key].present?
      @user = User.find_by_api_key(params[:api_key])

      return true if @user.present?
    end

    head :error
  end
end

app/controllers/api/commits_controller.rb
class Api::CommitsController < Api::ApiController
  def create
    if params[:repository].present?
      repository = @user.repositories.find_by_id(params[:repository])

      if repository.present?
        @user.commits.create(:repository_id => repository.id)
      else
        head :error and return
      end
    else
      @user.commits.create
    end

    head :ok
  end
end

app/controllers/api/repositories_controller.rb
class Api::RepositoriesController < Api::ApiController

  def create

    if params[:name].nil?
      response = {
        :error => {:code => 400, :message => "Parameter 'name' is required!"}
      }
      render :json => response, :status => :bad_request and return
    end
    
    @repository = @user.repositories.new(:name => params[:name])
    if @repository.save
      response = {
        :id => @repository.id,
        :name => @repository.name,
        :shortcode => @repository.shortcode
      }

      render :json => response, :status => :created
    else
      response = {
        :error => {
          :code => 400,
          :message => "The repository named '#{params[:name]}' already exists for this api key!"
        }
      }
      render :json => response, :status => :bad_request
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery

  before_filter :set_user_time_zone
  before_filter :ensure_domain

  private
  def set_user_time_zone
    Time.zone = current_user.time_zone if signed_in?
  end

  def ensure_domain
    if request.env['HTTP_HOST'] == 'hulkort.herokuapp.com'
      redirect_to "http://www.hulkort.com", status: 301
    end
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def show
    if params[:shortcode].present?
      @repository = Repository.find_by_shortcode(params[:shortcode])
      unless @repository.nil?
        @repository_daily_commits = @repository.commits.daily_commits.reverse
      else
        render :status => 500
      end
    else
      render :status => 500
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    unless params[:ignore_commits].present?
      redirect_to current_user if current_user.present? && current_user.commits.count > 0
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  private
  def url_after_destroy
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
    @time_limit = 30
    @commits = current_user.commits.limit_time_to(@time_limit.days.ago).order(:created_at).reverse_order

    @user_commit_count = current_user.commits.count
    @user_daily_commits = current_user.commits.daily_commits.reverse
    @global_commit_count = Commit.count
    @global_daily_commits = Commit.daily_commits.reverse
  end

  def update
    current_user.update_attributes(user_parameters)

    redirect_to action: :edit
  end

private
  def user_parameters
    params.require(:user).permit(:time_zone)
  end
end

app/helpers/api/commits_helper.rb
module Api::CommitsHelper
end

app/helpers/api/repositories_helper.rb
module Api::RepositoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/graphs/show.html.erb
<h2><%= @repository.name %></h2>
<div id="repository-commits-graph">
  <% @repository_daily_commits.each do |day| %>
    <div style="height: <%= day['count'] * 5 + 1 %>px;"></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hulkort</title>

  <meta charset="utf-8">
  <meta name="author" content="David Strauß">
  <meta name="author" content="Thomas Buchöster">
  <meta name="description" content="Hulkort helps you tracking your personal Git commit statistics.">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    "application" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,600,700,300' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= render 'shared/google_analytics' %>
</head>
<body lang="en">

  <%= render 'shared/user_navigation' %>

  <h1>Hulkort</h1>

  <section id="content">
    <%= yield %>
  </section>

  <% flash.each do |key, value| -%>
    <div class="flash <%= key %>"><%= value %></div>
  <% end -%>

  <footer>
    Built by <a href="http://stravid.com">David Strauß</a> & <a href="mailto:thomas.buchoester@gmail.com">Thomas Buchöster</a>
    <br>
    Questions? Ask us: <a href="mailto:hulkort@stravid.com">hulkort@stravid.com</a>
  </footer>
</body>
</html>

app/views/pages/index.html.erb
<% if current_user.present? %>
  <% display_api_key = current_user.api_key %>
<% else %>
  <% display_api_key = "3695627b56d99b0eb392131d" %>
<% end %>

<h2>Personal Git Commit Statistics</h2>
<p>
  Simply make a <code>POST</code> request to track your commits:
</p>
<pre>http://www.hulkort.com/api/commits/?api_key=<%= display_api_key %></pre>
<% unless current_user.present? %>
  <p>
    This is an example! Please <%= link_to "sign in", sign_in_path %> to see your personal URL and API key.
  </p>
<% end %>

<h2>Let's automate this!</h2>
<p>
  Git has so called <a href="http://book.git-scm.com/5_git_hooks.html">Git Hooks</a>! Simply put a hook is a script which is executed every time you use a certain git command. With the help of a <code>post-commit</code> hook it's easy to ping the Hulkort API automatically:
</p>
<pre>
<span># Create the post-commit hook somewhere</span>
mkdir ~/development/git-hooks
cd ~/development/git-hooks
echo '#!/bin/bash' >> post-commit
echo 'curl -d "api_key=<%= display_api_key %>" http://www.hulkort.com/api/commits' >> post-commit

<span># Set permissions so it can be executed</span>
chmod 755 post-commit

<span># Find the folder where Git stores it's templates</span>
<span># A good place to start looking is '/usr/share/git-core/'</span>
find /usr -type d -name "hooks"
/usr/share/git-core/templates/hooks

<span># Link the post-commit hook into your template hooks</span>
cd /usr/share/git-core/templates/hooks
ln -s ~/development/git-hooks/post-commit post-commit
</pre>
<p>
  From now on all new Git repositories you create will have the hook and will therefore track your commits. To add the hook to an already existing repository you just run <code>git init</code> again. Git will re-initialize the repository and copy the <code>post-commit</code> hook.
</p>

<h2>What happened?</h2>

<p>
  In order to get executed a hook has to be in the <code>.git/hooks</code> directory of the repository. Nobody wants to add the <code>post-commit</code> hook by hand to every new repository. Instead we use a template and let Git do all the work.
</p>

<p>
  Whenever you run <code>git init</code> Git will copy the template files into the repositorys <code>.git</code> directory.
</p>
<p>
  So all we have to do is place our <code>post-commit</code> hook in the <code>git-core/templates/hooks</code> directory. To make things clean we just link it, this way we can easily edit the hook anytime.
</p>

<h2>Example Graph</h2>
<br>
<%= image_tag('example-graph.png') %>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4308722-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_user_navigation.html.erb
<nav id="user-navigation">
  <% if signed_in? %>
    <%= link_to "Home", root_path(:ignore_commits => true) %> |
    <%= link_to "Statistics", user_path(current_user) %> |
    <%= link_to "Account Settings", edit_user_path(current_user) %> | 
    <%= link_to "Sign out", sign_out_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign in", sign_in_path %>
  <% end %>
</nav>

app/views/users/edit.html.erb
<h2>Account Settings</h2>

<p id="api-key">
  API key: <%= current_user.api_key %>
</p>

<%= form_for(current_user) do |form| %>
  <%= form.label :time_zone, "Time zone" %>
  <%= form.time_zone_select :time_zone, ActiveSupport::TimeZone.all %>
  <%= form.submit "Save" %>
<% end %>

app/views/users/show.html.erb
<h2>Your Statistics</h2>
<% unless @commits.empty? %>
<p>
  Total Commits: <%= @user_commit_count %>
</p>
<div id="user-commits-graph">
  <% @user_daily_commits.each do |day| %>
    <div style="height: <%= day['count'] * 5 + 1 %>px;"></div>
  <% end %>
</div>

<h2>Global Statistics</h2>
<p>
  Total Commits: <%= @global_commit_count %>
</p>
<div id="global-commits-graph">
  <% @global_daily_commits.each do |day| %>
    <div style="height: <%= day['count'] * 5 + 1 %>px;"></div>
  <% end %>
</div>

<h2>Commits Log</h2>
<p>During the last <%= @time_limit %> days you did exactly <%= @commits.count %> commits.</p>
<% else %>
<p>We didn´t track any data of you during the last <%= @time_limit %> days. So give it a try, or just begin again.</p>
<% end %>
<ul>
<% @commits.each do |commit| %>
  <li><%= commit.created_at.strftime('%I:%M%p on %e %B, %Y') %></li>
<% end %>
</ul>